apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "k8s-demo-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
        - name: "frontend"
          image: "k8s-demo-frontend"
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
